### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by Abhishek1896** [bunny98/Text-to-Image-Using-GAN#1]
Traceback (most recent call last):
  File "train.py", line 443, in <module>
    main()
  File "train.py", line 77, in main
    args.n_classes)
  File "train.py", line 247, in load_training_data
    open(join(data_dir, 'flowers', 'flowers_caps.pkl'), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Data/datasets/flowers/flowers_caps.pkl'

This is my error as there is no such file as flowerscaps.pkl  being created during preprocessing

**Comment by anandxkumar** [comment]
After downloading and extracting the required files run the following code to create the pkl file
python dataprep.py --data_dir=Data --dataset=flowers
Then train the model
